kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: deployment1
  template:
    metadata:
      labels:
        name: deployment1
    spec:
      containers:
        - name: c00
          image: shamashaik19/shaimage:latest
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: demoservices
spec:
  ports:
    - port: 8000
      targetPort: 80
  selector:
    name: deployment1
  type: NodePort
